databases: []

services:
  - type: web
    name: pitchpulse-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: USE_DEMO_DATA
        value: "True"
      - key: GEMINI_API_KEY
        sync: false
      - key: VECTOR_DB_URL
        value: ""
      - key: VECTOR_DB_TOKEN
        value: ""
      - key: PYTHON_VERSION
        value: "3.11.0"
